services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    platform: linux/amd64 
    container_name: soil_sql_server
    ports:
      - "1434:1433"
    environment:
      SA_PASSWORD: "300705ryA"
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Express"
    volumes:
      - sqlserverdata:/var/opt/mssql

volumes:
  sqlserverdata: